workflows:
  ios-workflow:
    name: iOS Build & Publish
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Tomas2

    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.tomashoca.app"
      node: 20
      xcode: 16.2
      cocoapods: default

    scripts:
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Set up keychain
        script: |
          keychain initialize

      - name: Set up code signing
        script: |
          app-store-connect certificates list \
            --type IOS_DISTRIBUTION \
            --certificate-key=@env:CM_CERTIFICATE_PRIVATE_KEY \
            --save || \
          app-store-connect certificates create \
            --type IOS_DISTRIBUTION \
            --certificate-key=@env:CM_CERTIFICATE_PRIVATE_KEY \
            --save
          keychain add-certificates

      - name: Use profiles
        script: |
          xcode-project use-profiles

      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
